# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: 'JiaPeng.SlidePace'
PackageVersion: '0.2.1'
InstallerType: 'inno'
Scope: 'user'
MinimumOSVersion: '10.0.19045.0'
UpgradeBehavior: 'install'
InstallModes:
- 'interactive'
- 'silent'
- 'silentWithProgress'
ReleaseDate: '2026-10-02'
Installers:
- Architecture: 'x64'
  ProductCode: '{a0d01205-281b-4773-9ef3-216ab3bede1a}_is1'
  InstallerUrl: 'https://github.com/hongjiapeng/SlidePace/releases/download/v0.2.1/SlidePace-0.2.1-win-x64-Setup.exe'
  InstallerSha256: C9AC5CB95286F4CA6EA5E463955E5EFB6022492C4067235E0E3A1F9D4F744319
ManifestType: installer
ManifestVersion: '1.12.0'
